<<<<<<< HEAD
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { SidebarProvider, Sidebar, SidebarTrigger, SidebarInset, SidebarHeader } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/toaster';
import Link from 'next/link';
import { Sparkles } from 'lucide-react';
import AppSidebarContent from '@/components/app-sidebar-content'; // New component for sidebar content
=======
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
>>>>>>> 5edd04a (initial scaffold)

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'CleanSweep App',
  description: 'Hospital Cleanliness Training & Inspection',
=======
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
>>>>>>> 5edd04a (initial scaffold)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={cn(geistSans.variable, geistMono.variable, 'antialiased font-sans')}>
        <SidebarProvider defaultOpen>
          <Sidebar side="left" variant="sidebar" collapsible="icon">
             <AppSidebarContent />
          </Sidebar>
          <SidebarInset>
            <header className="flex items-center justify-between p-4 border-b bg-card">
              <div className="flex items-center gap-2">
                 <SidebarTrigger className="md:hidden" />
                 <Link href="/" className="flex items-center gap-2 font-semibold text-lg text-primary">
                    <Sparkles className="w-6 h-6 text-primary" />
                    <span>CleanSweep</span>
                 </Link>
              </div>
              {/* Add User menu or other header items here if needed */}
            </header>
            <main className="flex-1 p-4 md:p-6 lg:p-8">
                {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
=======
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
>>>>>>> 5edd04a (initial scaffold)
      </body>
    </html>
  );
}
